route:
  group_by: ['alertname']
  group_wait: 5s       # Attendre 5s pour grouper les alertes
  group_interval: 5s   # Délai entre deux groupes d'alertes
  repeat_interval: 1h  # Ne pas spammer si ça reste cassé
  receiver: 'webhook-healer'

receivers:
  - name: 'webhook-healer'
    webhook_configs:
      # L'URL pointe vers le conteneur "webhook" sur le port 9000, 
      # et déclenche l'ID "restart-victim" défini dans ton hooks.json
      - url: 'http://webhook:9000/hooks/auto-restart'
        send_resolved: false