
 groups:
  - name: auto-remediation-alerts
    rules:
      - alert: ContainerDown
        # Au lieu de cibler un nom précis, on cible tous les jobs sauf prometheus lui-même
        expr: up{job!="prometheus"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Le conteneur {{ $labels.job }} est tombé"
          description: "Auto-remédiation requise pour {{ $labels.job }}."